In [1]:
import os
import pickle
import pandas as pd

In [4]:
data_dir = 'filtered_db_tab/'
files_to_read = os.listdir(data_dir)
print(files_to_read)
files_to_read.pop(4)

['EC3.tabular', 'EC2.tabular', 'EC7.tabular', 'EC5.tabular', '.ipynb_checkpoints', 'EC4.tabular', 'EC6.tabular', 'EC1.tabular']

'.ipynb_checkpoints'

In [5]:
for tab_data in files_to_read:
    print(tab_data)
    tab_dir = data_dir + tab_data
    df = pd.read_csv(tab_dir, delimiter='\t', header=None)
    print(df.head(3))
    c28_values = df[27].tolist()
    print('instances: ', len(c28_values))
    
    output_file_name = tab_dir.replace('.tabular', '.p')  # Change file extension to .p
    with open(output_file_name, 'wb') as file:
        pickle.dump(c28_values, file)
    print(f'{output_file_name} saved.')

EC3.tabular
           0       1       2    3    4   5   6    7    8    9   ...  18  19  \
0  A0A024SH76  Q8NJP6  71.875   32    9   0  31   62  351  382  ...   1   1
1  A0A024SIB3  G4MTF8  66.990  309  101   1  40  347   23  331  ...   1   1
2  A0A0A7HF73  P9WPJ1  30.645  248  161   5   1  239   57  302  ...   1   1

                                                  20  \
0                   WGQCGGQNWSGPTCCASGSTCVYSNDYYSQCL
1  ADLWDRQASQSIDQLIKRKGKLYFGTATDRGLLQREKNAAIIQADL...
2  MKKLVFTFKRIDHP-----AQDLAVKFHGFLMEQLDSDYVDYLHQQ...

                                                  21   22   23      24  25  \
0                   WGQCGGSGWTGPTVCESGYTCTYSNAWYSQCL  471  382  Q8NJP6   7
1  AELSARQAQQSIDALMKAKGKLYFGTATDQGLLNTGKNSAIIKADF...  347  331  G4MTF8  89
2  LSRLTLTLE-VDAPLERARVATLGPHLHGVLMESIPADYVQTLHTV...  243  314  P9WPJ1  98

   26                                                 27
0   1  MIVGILTTLATLATLAASVPLEERQACSSVWGQCGGQNWSGPTCCA...
1   1  MKANVILCLLAPLVAALPTETIHLDPELAALRANLTERTADLWDRQ...
2   1  MKKLVFTFKRIDHPAQDLAVKFHGFLMEQLDSDYVDYLHQQQTNPY...

[3 rows x 28 columns]
instances:  1263
filtered_db_tab/EC3.p saved.
EC2.tabular
           0           1       2    3    4   5   6    7   8    9   ...  18  \
0  A0A061FMF5  A0A061FKL9  67.778  360  113   2   1  358   3  361  ...   1
1  A0A084R1I1  A0A067Z9B6  41.250  400  224   7   1  390   1  399  ...   1
2  A0A0C1BWC7  A0A0F7TQP2  39.224  464  254  11   8  462  36  480  ...   1

   19                                                 20  \
0   1  MEVKEMLFMNKGDGENSYVKTSGYTQKVAAVTQPVVYRAAQSLFTG...
1   1  MASSVATLVKSLDKINAADFESDEAARVNAIAAAQKMIHRLQSGVE...
2   1  TMELILRFDDVIEPEKLRQSLGRLLEIGNWRKLGARVRPRENN-AG...

                                                  21   22   23          24  \
0  MKVKDIVFMNKGDGENSYVKSAGLTLKVIAKTQPIVQKAVQSLFTG...  363  367  A0A061FKL9
1  MADIAEQLIEKLQTLETSIFEGQDATRQKLALAARKLFHTLETKEE...  391  400  A0A067Z9B6
2  NVEVALRFDSSLDSEKLQQSLKQLLEIGNWRQLGGRVRRRDTNPSA...  470  482  A0A0F7TQP2

   25  26                                                 27
0  99   1  MEVKEMLFMNKGDGENSYVKTSGYTQKVAAVTQPVVYRAAQSLFTG...
1  99   1  MASSVATLVKSLDKINAADFESDEAARVNAIAAAQKMIHRLQSGVE...
2  97   1  MDCVCDETMELILRFDDVIEPEKLRQSLGRLLEIGNWRKLGARVRP...

[3 rows x 28 columns]
instances:  1844
filtered_db_tab/EC2.p saved.
EC7.tabular
       0       1       2    3    4   5   6    7   8    9   ...  18  19  \
0  A0PY57  Q0TNZ3  69.767  344  104   0   4  347   5  348  ...   1   1
1  A1JPQ1  Q6D654  56.048  248  109   0   4  251   1  248  ...   1   1
2  A1SSX2  A1JM66  55.301  349  148   3   6  350   4  348  ...   1   1

                                                  20  \
0  NIIEIKNVYKEFNGVPILKDINLNIKKNEFLTLLGPSGCGKTTTLR...
1  LQLSNVSVDTRLAPFSTQVAAGLQTHLIGPNGAGKSTLLASLAGLL...
2  ASSPHQKQRRTTSQVMVLVILCLIPGVFLQSYFFGYANLIQISLAC...

                                                  21   22   23      24  25  \
0  NIIELKGITKSYGKDTILDNLSLNIKKNEFLTLLGPSGCGKTTTLK...  347  349  Q0TNZ3  99
1  MQLRQASVLPRLSPTNAECRPGELLHIIGPNGAGKSTLLARAAGLL...  253  250  Q6D654  98
2  ASSPFTHNQRSTRSIMLLVILACIPGIIAQTYFFGYGSLIQVALAI...  350  351  A1JM66  99

   26                                                 27
0   1  MAENIIEIKNVYKEFNGVPILKDINLNIKKNEFLTLLGPSGCGKTT...
1   1  MMLLQLSNVSVDTRLAPFSTQVAAGLQTHLIGPNGAGKSTLLASLA...
2   1  MAYKNASSPHQKQRRTTSQVMVLVILCLIPGVFLQSYFFGYANLIQ...

[3 rows x 28 columns]
instances:  153
filtered_db_tab/EC7.p saved.
EC5.tabular
           0           1       2    3    4   5   6    7   8    9   ...  18  \
0  A0A0E4AYE7      S0DV66  61.497  374  143   1   1  374   1  373  ...   1
1  A0A0F7GGT4  A0A2Z5XAU0  35.787  394  219  14  13  396  15  384  ...   1
2  A0A455R4Z0  A0A0M4KRN2  28.715  397  245  11   1  373   1  383  ...   1

   19                                                 20  \
0   1  MSNVTVSAFTVDKSISEEHVLPSSFIPGSGNIFPKFTSAIPKTAWE...
1   1  ESITTDPIPESDFIPNSGNLFPKFPDQIRKTAVEVWLFDAIAEDGS...
2   1  MPQLAGKLILAGLIPLGAWVLHGFASCNGLIQM-FEDFGKQTVLSD...

                                                  21   22   23          24  \
0  MPAKTVSHLNFETSISTETVPASPYIPGSGNVFAKFVDAISQTGWE...  374  373      S0DV66
1  NCIIETPLQPSDFLPKSANLFPKFPERISVDSWELWEFDTFDTNGS...  397  386  A0A2Z5XAU0
2  MPQ-STKYILPVYGILALYSLGYFSYRNGYVNIVLEERQAWLDMPP...  384  383  A0A0M4KRN2

    25  26                                                 27
0  100   1  MSNVTVSAFTVDKSISEEHVLPSSFIPGSGNIFPKFTSAIPKTAWE...
1   97   1  MVDIFTSEFTVGESITTDPIPESDFIPNSGNLFPKFPDQIRKTAVE...
2   97   1  MPQLAGKLILAGLIPLGAWVLHGFASCNGLIQMFEDFGKQTVLSDG...

[3 rows x 28 columns]
instances:  275
filtered_db_tab/EC5.p saved.
EC4.tabular
           0           1       2    3    4   5   6    7   8    9   ...  18  \
0  A0A0H3KB22      Q9A3P3  65.714  210   72   0   1  210   1  210  ...   1
1  A0A0U2UYC4      E6LDH5  37.701  435  270   1  54  488  11  444  ...   1
2  A0A151ZEA6  A0A385AJM2  67.477  329  103   2   1  326   1  328  ...   1

   19                                                 20  \
0   1  MTYAVKEIFYTLQGEGANAGRPAVFCRFAGCNLWSGREEDRAQAVC...
1   1  LSDIFGTPQMREIWSDQNRVACYLEIEAALAIVQADLGIIPKNAAH...
2   1  MSLSLNDIKFPSSWDLSPNDLSYIDDIYQEGLDLGVWRKDNQRDKL...

                                                  21   22   23          24  \
0  MTYSVKEIFLTLQGEGGQAGKAAVFCRFSGCNLWSGREQDRAKAVC...  210  210      Q9A3P3
1  LRNNFSTAEMRAIWNDEARITKQLAVEAALAQAEGELGLIPKEAAK...  493  455      E6LDH5
2  MSLSLNDIKFPMHWNLDPNEFSYVEYVYREGLELGVWRPDNKRDQM...  353  332  A0A385AJM2

    25  26                                                 27
0  100   1  MTYAVKEIFYTLQGEGANAGRPAVFCRFAGCNLWSGREEDRAQAVC...
1   88   1  MAPALNANPTTKRDELSAPSASHKLGMSSMASRAAGGGLKLTGLPD...
2   92   1  MSLSLNDIKFPSSWDLSPNDLSYIDDIYQEGLDLGVWRKDNQRDKL...

[3 rows x 28 columns]
instances:  433
filtered_db_tab/EC4.p saved.
EC6.tabular
       0       1       2    3    4   5   6    7   8    9   ...  18  19  \
0  A0L7T9  A6VD51  60.047  428  169   2   3  430   4  429  ...   1   1
1  A0LA23  A3D3D1  62.248  347  127   3   8  353   2  345  ...   1   1
2  A0LF67  Q2LSQ5  59.498  279  113   0   1  279   1  279  ...   1   1

                                                  20  \
0  NVVIVGTQWGDEGKGKIVDLLTEQADMVVRFQGGHNAGHTLVVDGK...
1  SSPSGMTYRDAGVDIDAGNRLVSMIKRSVASTHRPEVRSDLGGFGA...
2  MRIIETVSEMQQQADDWRRAGKRIGFVPTMGYFHEGHLMLMRKVRG...

                                                  21   22   23      24  25  \
0  NVVVLGTQWGDEGKGKIVDLLTEQAAAVVRYQGGHNAGHTLVIDGE...  432  430  A6VD51  99
1  STPTPLSYKDAGVDIDAGNALVSNIKAAVKRTRRPEVMGNLGGFGA...  353  345  A3D3D1  98
2  MKIIHAVHEMQDYSEALRKAGRRIAFVPTMGYFHEGHLDLMREGRK...  283  286  Q2LSQ5  99

   26                                                 27
0   1  MSNVVIVGTQWGDEGKGKIVDLLTEQADMVVRFQGGHNAGHTLVVD...
1   1  MAHNQDASSPSGMTYRDAGVDIDAGNRLVSMIKRSVASTHRPEVRS...
2   1  MRIIETVSEMQQQADDWRRAGKRIGFVPTMGYFHEGHLMLMRKVRG...

[3 rows x 28 columns]
instances:  325
filtered_db_tab/EC6.p saved.
EC1.tabular
           0       1       2    3    4   5   6    7   8    9   ...  18  19  \
0  A0A059WLZ7  Q5S3I3  40.060  332  196   3   2  332   3  332  ...   1   1
1  A0A063C1W0  E9F647  53.543  127   59   0   5  131  12  138  ...   1   1
2  A0A068Q5V6  H2DH18  54.192  489  205   7  19  493  17  500  ...   1   1

                                                  20  \
0  FLQNAWYAVAWCDEVTDGIVTRKVLGRELALFRDGEGQPRAILNRC...
1  HQLLCLNILGFRKPGISTEDYRNYMVNVHAPLVAGLMEKYGFLHFT...
2  AWW-------KNKKKRLPPGPRGFPIFGSLHLLGEFPNKDLHRLAR...

                                                  21   22   23      24  25  \
0  FVRNAWYVAALPEELSEKPLGRTILDTPLALYRQPDGVVAALLDIC...  348  339  Q5S3I3  95
1  QQLLCLTITAFRKPGMSEAAYREYMTKTHAPLVSGLMEEYGIVRYN...  140  142  E9F647  91
2  SWWILPIISPLKRHHKLPPGPRGLPIIGSLHTLGALPHRTLQTLAK...  497  500  H2DH18  96

   26                                                 27
0   1  MFLQNAWYAVAWCDEVTDGIVTRKVLGRELALFRDGEGQPRAILNR...
1   1  MASHHQLLCLNILGFRKPGISTEDYRNYMVNVHAPLVAGLMEKYGF...
2   1  MVWIWATIGLLALVHILQAWWKNKKKRLPPGPRGFPIFGSLHLLGE...

[3 rows x 28 columns]
instances:  707
filtered_db_tab/EC1.p saved.